name: Java CI with Maven

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get versions data from repo
      run: wget -O maven-metadata.xml https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/ant-media-server/maven-metadata.xml       
    - name: Install jq
      run: sudo apt-get install jq -y
    - name: Download war File
      run: |
        export LATEST_SNAPSHOT=$(grep -oP '(?<=<version>)[^<]+' maven-metadata.xml| tail -1)
        echo $LATEST_SNAPSHOT
        echo "LATEST_SNAPSHOT=$LATEST_SNAPSHOT" >> $GITHUB_ENV
        wget -O ConferenceCall.war "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.antmedia.webrtc&a=ConferenceCall&v=${LATEST_SNAPSHOT}&e=war"
        ls -al
        if [ ! -f ConferenceCall.war ]; then
          echo "War file not found."
          exit 1
        fi
    - name: MD5 file checksum
      run: |
        echo $LATEST_SNAPSHOT
        wget -O ConferenceCall.md5 "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.antmedia.webrtc&a=ConferenceCall&v=${LATEST_SNAPSHOT}&e=war.md5"
        local_file_md5="$(md5sum ConferenceCall.war | awk '{print $1}')"
        remote_file_md5="$(cat ConferenceCall.md5)"
        
        if [ "$remote_file_md5" != "$local_file_md5" ]; then
          echo "MD5 checksum mismatch!"
          exit 1
        else
          echo "MD5 checksum matches."
        fi
